version: "3"
services:
  db:
    image: postgres:16.2
    volumes:
      - food_tracker_db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5432"

volumes:
  food_tracker_db_vol:
